# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployment_engine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import hlo_pb2 as hlo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x65ployment_engine.proto\x1a\thlo.proto\"\x9e\x01\n\x1aServiceComponentAllocation\x12\x44\n$old_allocated_infrastructure_element\x18\x01 \x01(\x0b\x32\x16.InfrastructureElement\x12:\n\x1fnew_allocated_service_component\x18\x02 \x01(\x0b\x32\x11.ServiceComponent\"^\n\x18HLODeploymentEngineInput\x12\x42\n\x1dservice_component_allocations\x18\x01 \x03(\x0b\x32\x1b.ServiceComponentAllocationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deployment_engine_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICECOMPONENTALLOCATION._serialized_start=39
  _SERVICECOMPONENTALLOCATION._serialized_end=197
  _HLODEPLOYMENTENGINEINPUT._serialized_start=199
  _HLODEPLOYMENTENGINEINPUT._serialized_end=293
# @@protoc_insertion_point(module_scope)
